# Generated by Django 3.0 on 2021-11-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_entry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_entry',
            name='img_id',
            field=models.ManyToManyField(related_name='img', to='shop.img'),
        ),
    ]
