# Generated by Django 3.0 on 2021-11-29 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_categor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_entry',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product_entry',
            name='categor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='انتخاب کتگوری'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_entry',
            name='description',
            field=models.TextField(default=1, verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_entry',
            name='material',
            field=models.CharField(choices=[('درجه یک', 'درجه یک'), ('متوسط', 'متوسط')], default=1, max_length=50, verbose_name='کیفیت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_entry',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=30, null=True, verbose_name='قیمت'),
        ),
        migrations.AddField(
            model_name='product_entry',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True, verbose_name='ادرس کالا'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
