# Generated by Django 3.0 on 2021-11-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20211129_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_entry',
            name='pic',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='عکس اصلی'),
            preserve_default=False,
        ),
    ]
