# Generated by Django 3.0 on 2021-12-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20211218_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.IntegerField(default=1, verbose_name='شماره همراه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=250, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code_posti',
            field=models.IntegerField(verbose_name='کدپستی'),
        ),
    ]
