# Generated by Django 3.0 on 2021-12-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20211218_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_percentage',
            field=models.IntegerField(default=0, verbose_name='تخفیف'),
        ),
    ]
