# Generated by Django 3.0 on 2021-12-22 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_item_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_percentage',
        ),
    ]
