# Generated by Django 3.0 on 2021-12-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_item_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_percentage',
            field=models.IntegerField(default=0, verbose_name='تخفیف'),
        ),
    ]
