# Generated by Django 3.0 on 2021-12-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20211222_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_discount',
            field=models.IntegerField(default=0, verbose_name='تخفیف'),
        ),
    ]
